import { readFile, stat } from "node:fs/promises";
import { join } from "node:path";

export type ReviewArtifact = {
  id: string;
  session: string;
  sourceUrl: string;
  sourcePage: string;
  questionNumber: string;
  bodyJa: string;
  choices: { key: string; order: number; textJa: string }[];
  correctAnswer: string;
  mappingStatus: "CLEAN" | "REVIEW_REQUIRED" | "OCR_FAILED";
  parseConfidence: number;
  needsVisualReview: boolean;
  manualVisualOverride?: boolean;
  issues: string[];
  risk: "P0" | "P1" | "P2";
  autoApprove: boolean;
  duplicate?: boolean;
};

const REVIEW_DIR = join(process.cwd(), "storage", "review");
let cache: { mtimeMs: number; byId: Map<string, ReviewArtifact> } | undefined;

/**
 * The review report is generated by scripts/ipa-exemption/review-pending.ts.
 * Keep this lookup server-only and fail closed when the report is unavailable.
 */
export async function getReviewArtifact(id: string) {
  const path = join(REVIEW_DIR, "pending-review-candidates.json");
  try {
    const fileStat = await stat(path);
    if (!cache || cache.mtimeMs !== fileStat.mtimeMs) {
      const rows = JSON.parse(await readFile(path, "utf8")) as ReviewArtifact[];
      cache = { mtimeMs: fileStat.mtimeMs, byId: new Map(rows.map((row) => [row.id, row])) };
    }
    return cache.byId.get(id) ?? null;
  } catch {
    return null;
  }
}

export function reviewPageFileName(artifact: Pick<ReviewArtifact, "session" | "sourcePage">) {
  if (!/^[a-z0-9-]+$/iu.test(artifact.session) || !/^\d+$/u.test(artifact.sourcePage)) return null;
  return `${artifact.session}-p${artifact.sourcePage}.png`;
}

export function reviewPagePath(artifact: Pick<ReviewArtifact, "session" | "sourcePage">) {
  const fileName = reviewPageFileName(artifact);
  return fileName ? join(REVIEW_DIR, "pages", fileName) : null;
}
